name: Build firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - adafruit_feather_nrf52840_express
        shield:
          - sofle_left
          - sofle_right

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install west
          sudo apt update && sudo apt install -y ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
          west init -l config
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build firmware
        run: |
          west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}
          path: build/zephyr/zmk.uf2
